add_newline = false

format="""\
    $directory\
    $lua\
    $python\
    $nodejs\
    $golang\
    $rust\
    $terraform\
    $kubernetes\
    $git_branch\
    $git_status\
    $git_state\
    $jobs\
    $character\
"""

[directory]
  style = "bold #81a1c1"
  truncation_length = 3
  truncate_to_repo = true
  home_symbol = "~"
  read_only = " "
  format = "[($path )]($style)[$read_only]($read_only_style)"

[lua]
  symbol = " "
  format ="[($symbol$version )]($style)"

[python]
  style = "yellow"
  symbol = " "
  format = '[($symbol${version}) (\($virtualenv\) )]($style)'

[nodejs]
  symbol = " "
  style = "green"
  format ="[($symbol$version )]($style)"

[rust]
  symbol = " "
  format = "[($symbol$version )]($style)"

[golang]
  symbol = " "
  format = "[($symbol$version )]($style)"

[git_branch]
  style = "bold #5e81ac"
  format = "[($symbol$branch )]($style)"

[git_status]
  style = "bold #d08770"
  ahead = " $count"
  diverged = "${ahead_count}|${behind_count}"
  behind = " ${count}"

[git_state]
  format = "[($state( $progress_current of $progress_total ))]($style) "

[terraform]
  format = '[$symbol $workspace]($style) '
  symbol = '󱁢 '

[kubernetes]
  format = '[$symbol ctx:$context|ns:$namespace]($style) '
  symbol = '󱃾 '
  disabled = false
  detect_files = ["Chart.yaml", "values.yaml"]
  contexts = [
    { context_pattern = "dev-izi-compute-cluster", style="green", context_alias = "dev"},
    { context_pattern = "staging-izi-compute-cluster", style="yellow", context_alias = "staging"},
    { context_pattern = "prod-izi-compute-cluster", style="red", context_alias = "prod"},
  ]

[character]
  success_symbol = "[➜](green)"
  error_symbol = "[✗](red)"
  vicmd_symbol = "[«](cyan)"
