" PLUGIN MANAGER
if empty(glob('~/.config/nvim/vim-plug/plug.vim'))
  silent !curl -fLo ~/.config/nvim/vim-plug/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $VIMRC
endif

" Specify directory for plugins: VERY IMPORTANT TO USE SINGLE QUOTES
call plug#begin('$VIMPLUG')

Plug 'arcticicestudio/nord-vim'

Plug 'scrooloose/nerdtree'
autocmd vimenter * if !argc() | NERDTree | endif " Open NERDTree automatically on startup and move cursor to file
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif " Close vim if NERDTree is the only window
nnoremap <silent> <C-\> :NERDTreeToggle<CR>
let NERDTreeQuitOnOpen = 1
let NERDTreeAutoDeleteBuffer = 1
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1
let NERDTreeShowHidden = 1
let NERDTreeIgnore = ['\.pyc$', '__pycache__/', '.git/', '\.swp$']

Plug 'scrooloose/nerdcommenter'

Plug 'vim-airline/vim-airline' "Status Line

Plug 'tpope/vim-fugitive'
set diffopt+=vertical " Make vim-fugitive open vertical diff instead of horizontal

Plug 'airblade/vim-gitgutter'
Plug 'Xuyuanp/nerdtree-git-plugin'

Plug 'ycm-core/YouCompleteMe', {'do': './install.py'}

Plug 'vim-syntastic/syntastic'
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_w = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_auto_jump = 0
let g:syntastic_python_checkers = ['flake8']

nnoremap <silent> <F8> <ESC>:call SyntasticToggle()<CR>

let g:syntastic_is_open = 0
function! SyntasticToggle()
    if g:syntastic_is_open == 1
        lclose
        let g:syntastic_is_open = 0
    else
        Errors
        let g:syntastic_is_open = 1
    endif
endfunction

Plug 'Yggdroot/indentLine'
let g:indentLine_char_list = ['|', '¦', '┆', '┊']

" Other plugins
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'wlemuel/vim-tldr'

Plug 'lervag/vimtex' " https://github.com/lervag/vimtex

call plug#end() " Finished Initialising Plugins

" Reload vimrc
nnoremap <leader>r :source $VIMRC<CR>
" vimrc config from https://github.com/changemewtf/no_plugins/blob/master/no_plugins.vim
set nocompatible
filetype plugin on
syntax on

" Set the colorscheme
colorscheme nord

" Autoreload files
set autoread

" Encoding and file format
set encoding=utf-8
set fileformat=unix
"
" Set Mouse to integrate with the rest of the GUI
set mouse=a " a for all
set cursorline
set nu
set scrolloff=2
set noshowmode
set showcmd
set noswapfile
set nowrap
set splitright
set splitbelow
set clipboard=unnamed

" More natural split navigation
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Search recenters cursor
nnoremap n nzz
nnoremap N Nzz
nnoremap * *zz
nnoremap # #zz
nnoremap g* g*zz
nnoremap g# g#zz

" Highlight search result and remap :nohs
nnoremap <silent> <leader><space> :noh<CR>
set hlsearch
set incsearch
set ignorecase
set smartcase

" Python configuration for tabs and spaces and all that
set smartindent
set expandtab
set smarttab
autocmd FileType python set sw=4 ts=4 softtabstop=4 expandtab smartindent
autocmd FileType python match ErrorMsg '\%>120v.\+'
" set different tabs for yaml and json
autocmd FileType yaml set sw=2 ts=2 softtabstop=2 expandtab smartindent
autocmd FileType json set sw=2 ts=2 softtabstop=2 expandtab smartindent

" Remove trailing spaces
nnoremap <silent> <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar><CR>

" Add JIRA issue to commit message 
nnoremap <silent> <leader>g :normal 5gg5wy$ggp<CR>a
nnoremap <silent> <leader>bg :normal 5gg3wy$ggp<CR>a

" Format a json file
nnoremap <silent> <leader>j :%!python -m json.tool<CR>

" Search down into subfolders
set path+=**

" Provides tab-completion for all related tasks
set wildmenu

