" PLUGIN MANAGER
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Specify directory for plugins
call plug#begin('~/.vim/plugged')

" VERY IMPORTANT TO USE SINGLE QUOTES
" NerdTree for stuff
Plug 'scrooloose/nerdtree'

" Git Integration
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'Xuyuanp/nerdtree-git-plugin'

" Python Plugins
" Using Jedi-Vim for python related stuff
" Flake8 and isort
Plug 'davidhalter/jedi-vim'
Plug 'vim-syntastic/syntastic'

" Other plugins
Plug 'scrooloose/nerdcommenter'
Plug 'itchyny/lightline.vim'
Plug 'jiangmiao/auto-pairs'
Plug 'Yggdroot/indentLine'
Plug 'tpope/vim-unimpaired'

"https://github.com/lervag/vimtex
Plug 'lervag/vimtex'

" Yet another color scheme
Plug 'morhetz/gruvbox'

" Finished Initialising Plugins
call plug#end()

" Set Mouse to integrate with the rest of the GUI
set mouse=a " a for all

" Set color scheme
set background=dark
colorscheme gruvbox

" Misc
" Encoding
set encoding=utf-8
set fileformat=unix
" Show line numbers
set nu
" Show commands being typed in normal mode
set showcmd
" Highlight search result and remap :nohs
set hlsearch
nnoremap <leader><space> :noh<CR>
"Do not wrap lines
set nowrap

" Python configuration for tabs and spaces and all that
set smartindent
set shiftwidth=4
set expandtab
set tabstop=4
set smarttab

" More natural split navigation
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
" Open splits to the right
set splitright
set splitbelow

" vimrc config from https://github.com/changemewtf/no_plugins/blob/master/no_plugins.vim
set nocompatible
syntax enable
filetype plugin on

" Search down into subfolders
" Provides tab-completion for all related tasks 
set path+=**
set path+=~/local

" Display all matching files when tab completing
set wildmenu

" lightline.vim 
set laststatus=2

" Indentation guide config
let g:indentLine_char_list = ['|', '¦', '┆', '┊']

" NERDTree Configuration
" Open NERDTree automatically on startup and move cursor to file
autocmd vimenter * if !argc() | NERDTree | endif
" Close vim if NERDTree is the only window
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
" Map CTRL+\ to open NERDTree
map <C-\> :NERDTreeToggle<CR>
" Configs for NERDTree
let NERDTreeQuitOnOpen = 1
let NERDTreeAutoDeleteBuffer = 1
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1
let NERDTreeShowHidden = 1
let NERDTreeIgnore = ['\.pyc$', '__pycache__/', '.git/', '\.swp$']

" Nerdcommenter configs

" Fugitive configurations
set diffopt+=vertical " Make vim-fugitive open vertical diff instead of horizontal

" Syntastic configuration
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_w = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_auto_jump = 0
let g:syntastic_python_checkers = ['flake8']

map <F8> <ESC>:call SyntasticToggle()<CR>

let g:syntastic_is_open = 0
function! SyntasticToggle()
    if g:syntastic_is_open == 1
        lclose
        let g:syntastic_is_open = 0 
    else
        Errors
        let g:syntastic_is_open = 1
    endif
endfunction
