#!/usr/bin/bash

BRANCH=$(git rev-parse --abbrev-ref HEAD)
CONSOLE_DOT_LOG=$(rg 'console\.log')
HT_PATH="$HOME/code/hybrid-theory"

if [[ "$BRANCH" =~ (develop|master|main) ]] && [[ "$PWD" =~ $HT_PATH ]]; then
	echo "You can't commit directly to $BRANCH"
	exit 1
fi

if [[ $(rg '(?:it|describe)\.only') && "$PWD" =~ $HT_PATH ]]; then
	echo '"only" detected!'
	exit 1
fi

if [[ "$CONSOLE_DOT_LOG" && "$PWD" =~ $HT_PATH ]]; then
	echo "'console-dot-log' found!"
	echo "$CONSOLE_DOT_LOG"
	exit 1
fi

# vim: ft=sh
