#!/usr/bin/bash

BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [[ "$BRANCH" =~ ^(?:develop|master|main)$ ]]
then
    echo "You can't commit directly to $BRANCH branch"
    exit 1
elif [[ $(rg '(?:it|describe)\.only') ]]
then
    echo '"only" detected!'
    exit 1
elif [[ $(rg 'console\.log') ]]
then
    echo "'console-dot-log' found!"
    exit 1
fi

# vim: ft=sh
