#!/usr/bin/bash

BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [[ "$PWD" =~ "dotfiles" ]]
then
    if  [[ "$BRANCH" =~ "dev" ]]
    then
        # Prevent me from committing to dev
        # Commits should be made on main on the dotfiles repo.
        echo "Do you really want to commit to dev?"
        echo "Commit to main branch and then rebase dev."
        exit 1
    fi
elif [[ "$BRANCH" =~ develop|master|main ]]
  then
  echo "You can't commit directly to $BRANCH branch"
  exit 1
fi

# vim: ft=sh
