#!/usr/bin/bash

GIT_COMMIT_FILE=$1

if [[ "$PWD" =~ $DEV  ]]
then
    # Adds JIRA issue key into the commit message
    ISSUE_KEY=$(git rev-parse --abbrev-ref HEAD | cut -d "/" -f2)
    echo -e "$ISSUE_KEY " | cat - "$GIT_COMMIT_FILE" > "$GIT_COMMIT_FILE".tmp
    mv "$GIT_COMMIT_FILE".tmp "$GIT_COMMIT_FILE"
fi


# vim: ft=sh
