#!/bin/bash
# This hook is sourced after a new virtualenv is activated.

pip install -r requirements/flake8.txt --pre
pip install -e .
pip install pdbpp flake8 pycodestyle autoflake --upgrade
pip install isort ipdb\
    docformatter\
    pep8-naming\
    flake8-isort\
    flake8-breakpoint\
    flake8-mutable\
    flake8-commas\
    flake8-string-format\
    flake8-variables-names\
    flake8-bugbear

flake8 --install-hook=git

