#!/bin/bash
# This hook is sourced after every virtualenv is activated.

# Pytest Aliases
alias pytall='pytest -nauto -qk "" --cov ${PWD##*/} --cov-report term-missing'
alias pytdbg='pytest -lvxs'

export RP_CONFIG_SERVER_URL=http://bots-config.dev.redpoints.com
export SHOW_WARNINGS=True

# IPython debugger
export PYTHONBREAKPOINT=ipdb.set_trace
export PYTHONSTARTUP=$WORKON_HOME/pythonstartup.py
export PYTHONDONTWRITEBYTECODE=1

# Send HTML to file
export PATH_TO_HTML=.

