#!/bin/zsh
# This hook is sourced after a new virtualenv is activated.

PYPROJECT_FILE="pyproject.toml"
PRE_COMMIT_FILE=".pre-commit-config.yaml"
REQUIREMENTS_FILE="requirements.txt"

pip install --upgrade pip

if [[
	-f $PYPROJECT_FILE &&
	$(
		grep 'tool.poetry' $PYPROJECT_FILE >/dev/null && test $? -eq 0
	) ]]; then
	pip install "poetry<1.2" --upgrade
	poetry install --no-root
fi
if test -f $REQUIREMENTS_FILE; then

	pip install -r "$REQUIREMENTS_FILE"
fi

if test -f $PRE_COMMIT_FILE && $(command -v pre-commit); then
	pre-commit install
fi

if test $(pip show pytest &>/dev/null); then
	pip install pytest-sugar pytest-xdist
fi

# vi ft=sh
