#!/bin/zsh
# This hook is sourced after a new virtualenv is activated.


if [[ -z $LOCALVENV && $PWD =~ $HOME/rp ]]; then
    echo -n "Installing requirements and additional stuff... "
    pip install --quiet --upgrade pip
    pip install --quiet --pre -r requirements/flake8.txt -e .
    pip install --quiet ipython==7.9.0 ipdb==0.12.2 \
        flake8 flake8-breakpoint flake8-mutable flake8-variables-names flake8-bugbear
    cp $DOTFILES/python/isort.cfg .isort.cfg
    cp $DOTFILES/python/blak-config.toml pyproject.toml
    echo "Done!"
fi
