#!/bin/zsh
# This hook is sourced after a new virtualenv is activated.

pip install ipdb pdbpp flake8

if [[ -z $LOCALVENV ]]; then
    pip install -r requirements/flake8.txt --pre
    pip install -e .
    pip install pycodestyle autoflake --upgrade
    pip install pep8-naming\
        flake8-isort\
        flake8-breakpoint\
        flake8-mutable\
        flake8-string-format\
        flake8-variables-names\
        flake8-bugbear

    flake8 --install-hook=git
fi
