#!/bin/bash
# This hook is sourced before every virtualenv is deactivated.

if [[ "$(command -v pytest)" ]]
then
    unalias pa
    unalias pc
    unalias pd
    unalias pu
fi

if [[ -z $LOCALVENV && $PWD =~ $HOME/dev ]]; then
    unset RP_CONFIG_SERVER_URL
    unset PATH_TO_HTML
    unset LOG_LEVEL
fi
