#!/bin/bash
# This hook is sourced before every virtualenv is deactivated.

unalias pytall
unalias pytdbg

if [[ -z $LOCALVENV && $PWD =~ $HOME/rp ]]; then
    unset RP_CONFIG_SERVER_URL
    unset PYTHONBREAKPOINT
    unset PYTHONDONTWRITEBYTECODE
    unset PATH_TO_HTML
    unset LOG_LEVEL
fi
