#!/bin/zsh
# This hook is run before a virtualenv is deleted.
# argument: full path to environment directory

DIRNAME=$1

if [[ -v $DIRNAME ]]; then
    PATH=`find $DEV -name $DIRNAME -type d | head -1`
    command rm -rf $PATH/.git/hooks/pre-commit
fi
