#          | |
#   _______| |__   ___ _ ____   __
#  |_  / __| '_ \ / _ \ '_ \ \ / /
#   / /\__ \ | | |  __/ | | \ V /
#  /___|___/_| |_|\___|_| |_|\_/
#
export DOTFILES="$HOME/.config/dotfiles"
export DEV="$HOME/code"
export MAIN_SCREEN="DP-2"
export SECONDARY_SCREEN="DP-3"

export EDITOR="nvim"
export PAGER="less -RF"
export MANPAGER='nvim +Man!'
export BROWSER="firefox"
export FILE="nautilus"
export HISTFILE="$HOME/.local/zsh_history"

export ADOTDIR="$HOME/.local/share/antigen"
export ANTIGEN_BUNDLES="$HOME/.local/share/bundles"
export LOCAL_SH="$HOME/.local/local.sh"

export PYTHONBREAKPOINT="ipdb.set_trace"
export PIP_REQUIRE_VIRTUALENV=true
export PYTHONSTARTUP="$DOTFILES/python/pythonstartup.py"
export PYTHONDONTWRITEBYTECODE=1

export STARSHIP_CONFIG="$DOTFILES/starship/starship.toml"
export CARGO_HOME="$HOME/.local/share/cargo"
export RUSTUP_HOME="$HOME/.local/share/rustup"
export GOPATH="$HOME/.local/share/go"
export NVM_DIR="$HOME/.nvm"
export BAT_CONFIG_PATH="$DOTFILES/bat/config"
export RIPGREP_CONFIG_PATH="$DOTFILES/ripgrep/config"
export DOCKER_BUILDKIT=1
export FLYCTL_INSTALL="$HOME/.fly"

export NVIM_CONFIG="$DOTFILES/nvim"
export NVIM_PLUGINS_CONFIG="$NVIM_CONFIG/plugins"

export FORGIT_NO_ALIASES='nopls'
export FORGIT_INSTALL_DIR="$ANTIGEN_BUNDLES/wfxr/forgit"
export FORGIT_ADD_FZF_OPTS='--header="Add files"'
export FORGIT_DIFF_FZF_OPTS='--header="Git Diff"'
export FORGIT_LOG_FZF_OPTS='--header="Git Log"'
export FORGIT_CHECKOUT_BRANCH_FZF_OPTS='--header="Switch Branch"'
export FORGIT_FZF_DEFAULT_OPTS="
--height='80%'
--bind='alt-k:preview-page-up'
--bind='alt-j:preview-page-down'
--bind='alt-w:toggle-preview-wrap'
--bind='?:toggle-preview'
--preview-window='right:60%'
"

export ZSH_AUTOSUGGEST_STRATEGY=(history)
export ZSH_AUTOSUGGEST_USE_ASYNC=parallel
