#          | |
#   _______| |__   ___ _ ____   __
#  |_  / __| '_ \ / _ \ '_ \ \ / /
#   / /\__ \ | | |  __/ | | \ V /
#  /___|___/_| |_|\___|_| |_|\_/
#
export DOTFILES="$HOME/.config/dotfiles"
export DEV="$HOME/code"
export MAIN_SCREEN="DP-1"
export SECONDARY_SCREEN="DP-2"
export LAPTOP_SCREEN="eDP-1"
export MAIN_SCREEN="HDMI-1"
export SECONDARY_SCREEN=""

export EDITOR="nvim"
export PAGER="less -RF"
export MANPAGER='nvim +Man!'
export BROWSER="chromium-browser"
export FILE="nautilus"
export HISTFILE="$HOME/.local/zsh_history"

export ADOTDIR="$HOME/.local/share/antigen"
export ANTIGEN_BUNDLES="$HOME/.local/share/bundles"
export LOCAL_SH="$HOME/.local/local.sh"

export PYTHONBREAKPOINT="ipdb.set_trace"
export PIP_REQUIRE_VIRTUALENV=true
export PYTHONSTARTUP="$DOTFILES/python/pythonstartup.py"
export PYTHONDONTWRITEBYTECODE=1

export STARSHIP_CONFIG="$DOTFILES/starship/starship.toml"
export CARGO_HOME="$HOME/.local/share/cargo"
export RUSTUP_HOME="$HOME/.local/share/rustup"
export GOPATH="$HOME/.local/share/go"
export NVM_DIR="$HOME/.nvm"
export BAT_CONFIG_PATH="$DOTFILES/bat/config"
export RIPGREP_CONFIG_PATH="$DOTFILES/ripgrep/config"
export DOCKER_BUILDKIT=1
export FLYCTL_INSTALL="$HOME/.fly"

export NVIM_CONFIG="$DOTFILES/nvim"
export NVIM_PLUGINS_CONFIG="$NVIM_CONFIG/plugins"
